name: CI

on:
  pull_request:
    branches: [ main, hotfix/SusErrores ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # BACKEND (Spring Boot)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build back
        working-directory: back/McRonalds
        run: mvn -B verify

      # FRONTEND (React)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install front dependencies
        working-directory: front/mcrondaldsfront
        run: npm ci

      - name: Lint front
        working-directory: front/mcrondaldsfront
        run: npm run lint --if-present

      - name: Test front
        working-directory: front/mcrondaldsfront
        run: npm test --if-present -- --watchAll=false

      - name: Build front
        working-directory: front/mcrondaldsfront
        run: npm run build