name: CI

on:
  push:
    branches:
      - hotfix/SusErrores
  pull_request:
    branches:
      - main
      - hotfix/SusErrores

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ============================
      # FRONTEND (React)
      # ============================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: front/mcrondaldsfront/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./front/mcrondaldsfront
        run: npm install

      - name: Build Frontend
        working-directory: ./front/mcrondaldsfront
        run: npm run build

      # ============================
      # BACKEND (Spring Boot)
      # ============================
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build Backend
        working-directory: ./back
        run: mvn -B clean package