spring.application.name=McRonalds
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
mercadopago.token=APP_USR-7332701054623871-092411-fabb4903bcc956b199e63e3e0be151cd-2711766388
spring.datasource.url=jdbc:mysql://localhost:3306/mcronalds?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
mercadopago.backurl.success=http://localhost:8080/api/mercadopago/success
mercadopago.backurl.failure=http://localhost:8080/api/mercadopago/failure
mercadopago.backurl.pending=http://localhost:8080/api/mercadopago/pending
mercadopago.notificationUrl=http://localhost:8080/api/mercadopago/webhook
