spring.application.name=McRonalds
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.ssl=true
mercadopago.token=APP_USR-7332701054623871-092411-fabb4903bcc956b199e63e3e0be151cd-2711766388

spring.datasource.url=jdbc:postgresql://dpg-d4ef376r433s738m3pr0-a.oregon-postgres.render.com/mcronalds
spring.datasource.username=mcronalds_user
spring.datasource.password=zMFxttheqrScpYh4rklsHkxgq78aGAAx

# URLs con ngrok - FUNCIONAN CON MERCADOPAGO
mercadopago.backurl.success=https://ricarda-unresolute-giovanna.ngrok-free.dev/api/mercadopago/success
mercadopago.backurl.failure=https://ricarda-unresolute-giovanna.ngrok-free.dev/api/mercadopago/failure
mercadopago.backurl.pending=https://ricarda-unresolute-giovanna.ngrok-free.dev/api/mercadopago/pending
mercadopago.notificationUrl=https://ricarda-unresolute-giovanna.ngrok-free.dev/api/mercadopago/webhook

