# Application Name
spring.application.name=McRonalds

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mcronalds?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Server Port
server.port=8080

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost,http://localhost:80,http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# MercadoPago Configuration
mercadopago.token=${MERCADOPAGO_TOKEN:APP_USR-7332701054623871-092411-fabb4903bcc956b199e63e3e0be151cd-2711766388}
mercadopago.backurl.success=${MERCADOPAGO_SUCCESS_URL:http://localhost:8080/api/mercadopago/success}
mercadopago.backurl.failure=${MERCADOPAGO_FAILURE_URL:http://localhost:8080/api/mercadopago/failure}
mercadopago.backurl.pending=${MERCADOPAGO_PENDING_URL:http://localhost:8080/api/mercadopago/pending}
mercadopago.notificationUrl=${MERCADOPAGO_NOTIFICATION_URL:http://localhost:8080/api/mercadopago/webhook}